### ISSUE TITLE
Font and favicon 

### ISSUE THREAD

**Issue by durgaprasad118** [AlgoManiacZ/AlgoManiacZ_Revamped#13]
- Changing font to **Poppins**  whole web page
- Adding favicon
- Also adding colors in tailwind config file instead of using `[#xyz]` in each  component 
I would like to make this changes. 
Thankyou.

**Comment by Akshatchaube01** [comment]
Sure, go ahead

**Comment by durgaprasad118** [comment]
@Akshatchaube01  from next time 
Add hactoberfest and hactoberfest-accepted both the labels
