### ISSUE TITLE
Functionality & Smooth Scroll - Navbar

### ISSUE THREAD

**Issue by tejanamala15** [AlgoManiacZ/AlgoManiacZ_Revamped#17]
Would like to add in page navigation and smooth scroll in navbar.

**Comment by Akshatchaube01** [comment]
You can start working on this 👍

**Comment by ujjwalshivhare** [comment]
Hello Sir ,
can you assign me this?

**Comment by Akshatchaube01** [comment]
The issue has been resolved #23
