### ISSUE TITLE
add steps to open pr in readme

### ISSUE THREAD

**Issue by karthiknadar1204** [AlgoManiacZ/AlgoManiacZ_Revamped#21]
Add step by step process to create a pr in the project using shell commands for beginners to easily navigate and open a pr in the project

**Comment by durgaprasad118** [comment]
Also it would be great to create a branch and then make changes accordingly @karthiknadar1204  @Akshatchaube01

**Comment by karthiknadar1204** [comment]
Yes,add the steps to create a new branch like wise and push the changes

**Comment by durgaprasad118** [comment]
Can I do that changes to readme @karthiknadar1204 
1. Adding step by step process to create branch 
2. Making pr

**Comment by Akshatchaube01** [comment]
Sure !

**Comment by durgaprasad118** [comment]
@Akshatchaube01  @karthiknadar1204  I would like to add your profiles in the readme as project maintainers. What do you say?
