### ISSUE TITLE
Navbar issue 

### ISSUE THREAD

**Issue by Hardik2972** [AlgoManiacZ/AlgoManiacZ_Revamped#29]
# Currently 
In the small screen when we click on navicon and then click on any of the items (about us, speakers, FAQS,  join us, contact us)
the navbar is not removed automatically which is annoying
### Before click  -  
![Screenshot 2023-10-09 002524](https://github.com/AlgoManiacZ/AlgoManiacZ_Revamped/assets/115338787/c2b341fb-55e5-4364-89f5-dab96aedf24e)
### After  click  on join us- 
![image](https://github.com/AlgoManiacZ/AlgoManiacZ_Revamped/assets/115338787/eb63c386-2a36-4b94-babf-4e7472d8d566)

# Expected
### Before click  - 
![Screenshot 2023-10-09 002524](https://github.com/AlgoManiacZ/AlgoManiacZ_Revamped/assets/115338787/c2b341fb-55e5-4364-89f5-dab96aedf24e)
### After click on join us - 
![image](https://github.com/AlgoManiacZ/AlgoManiacZ_Revamped/assets/115338787/abf09f43-1eb9-4ea8-87a1-86517523914b)

### I would like to fix this bug in navbar

**Comment by Akshatchaube01** [comment]
Alright, go ahead
