### ISSUE TITLE
Building the complete site

### ISSUE THREAD

**Issue by Jony-Jas** [AlgoManiacZ/AlgoManiacZ_Revamped#3]
🏁 ☑️Tasks to build the site

- [ ] Home page 
- [ ] About Us page
- [ ] speakers
- [ ] Join Us
- [ ] Faq
- [ ] Contact us page

**Comment by Jony-Jas** [comment]
can you provide with the assets, font style and color info

**Comment by Akshatchaube01** [comment]
Feel free to choose any font size and color of your choice for now, we will change it as per our needs. The assets - (speaker images etc are all available in the repo itself)
And please work on one task per issue. You can raise another issue for each one of them .
