### ISSUE TITLE
Remove phone number from the footer and replace with email id

### ISSUE THREAD

**Issue by karthiknadar1204** [AlgoManiacZ/AlgoManiacZ_Revamped#35]
<img width="1786" alt="Screenshot 2023-10-15 at 7 14 06 PM" src="https://github.com/AlgoManiacZ/AlgoManiacZ_Revamped/assets/95973644/93feeba3-e75a-4c0a-96cf-2ab1d84a21e6">

akshat chaube->akshatchaube22@gmail.com
karthik nadar->karthiknadar1204@gmail.com

**Comment by gautamb02** [comment]
Hey,

I can help in this!! Assign me this one
