### ISSUE TITLE
Place the footer text in the center of the footer

### ISSUE THREAD

**Issue by karthiknadar1204** [AlgoManiacZ/AlgoManiacZ_Revamped#36]
<img width="1792" alt="Screenshot 2023-10-15 at 7 15 25 PM" src="https://github.com/AlgoManiacZ/AlgoManiacZ_Revamped/assets/95973644/7259c941-4ff2-43d2-ab97-fc7c3cbf1af9">

**Comment by govardhan-26** [comment]
I would like to work on this issue...please assign this to me

**Comment by Akshatchaube01** [comment]
@govardhan-26 go ahead

**Comment by sikehish** [comment]
Is the issue resolved? If not Id love to work on it

**Comment by sikehish** [comment]
Hi. The issue is fixed. https://github.com/AlgoManiacZ/AlgoManiacZ_Revamped/pull/60
