### ISSUE TITLE
Scroll to top button bug

### ISSUE THREAD

**Issue by karthiknadar1204** [AlgoManiacZ/AlgoManiacZ_Revamped#37]
The 'scroll to top button' is directly placed on the footer, we want it to be dynamic I.e when someone scrolls down, the button should appear dynamically and move the user back to the top of the screen.

<img width="1761" alt="Screenshot 2023-10-15 at 7 17 05 PM" src="https://github.com/AlgoManiacZ/AlgoManiacZ_Revamped/assets/95973644/7f0d488c-c0d5-487f-a7aa-940ce5776ae5">

When making the pr, make sure to attach a demo video of the changes implemented

**Comment by hemanth110702** [comment]
Hey, I would like to work on this. Can you please assign this to me?

**Comment by Akshatchaube01** [comment]
Sure, go ahead !
