### ISSUE TITLE
Add hover effect on the cards and on the social icons in the cards

### ISSUE THREAD

**Issue by karthiknadar1204** [AlgoManiacZ/AlgoManiacZ_Revamped#38]
<img width="1783" alt="Screenshot 2023-10-15 at 7 21 15 PM" src="https://github.com/AlgoManiacZ/AlgoManiacZ_Revamped/assets/95973644/57cfb267-79cb-4efa-8bc2-d84217006cd4">

**Comment by J11tendra** [comment]
Hello, Akshat! I would love to contribute to this issue.

**Comment by krishnas005** [comment]
Hello, I can contribute to this issue and make it better.

**Comment by ayush-pandey1** [comment]
Hey @Akshatchaube01 ,

i can contribute to this issue

**Comment by Akshatchaube01** [comment]
Issues are assigned on first come first serve basis, so I am assigning this issue to @J11tendra

**Comment by ayush-pandey1** [comment]
Hey @Akshatchaube01,

If this issue isn't solved yet, could you please assign it to me? I think the current assignee isn't active right now.

**Comment by Akshatchaube01** [comment]
@ayush-pandey1 I am assigning this issue to you
