### ISSUE TITLE
Add hover effects 

### ISSUE THREAD

**Issue by karthiknadar1204** [AlgoManiacZ/AlgoManiacZ_Revamped#39]
Add hover effects to the social media icons such that the icons on hovering turn to the original colour of the logo along with some scaling effects as well
<img width="1789" alt="Screenshot 2023-10-15 at 7 24 17 PM" src="https://github.com/AlgoManiacZ/AlgoManiacZ_Revamped/assets/95973644/9de59251-12c9-4b2b-a4f7-d7e8dc4a1f94">

**Comment by ayush-pandey1** [comment]
Hey Akshat,

Myself Ayush, i'm new to github and open-source-contributions. I've experience in building front-ends in react using HTML, Tailwind, CSS.

I would like to contribute in your project let me know if i can work on this issue.

I have cloned your project to my local machine, and do i've to make icon change its color to it's orignal (like blue for linkedin)   , let me know if i can contribute

**Comment by J11tendra** [comment]
Hello, Akshat! I would love to contribute to this issue.

**Comment by Akshatchaube01** [comment]
@Ayush80555 Okay go ahead !

**Comment by AkshitMital** [comment]
Hey @Akshatchaube01, Can you please check my Pull Request?

**Comment by Akshatchaube01** [comment]
I have assigned this issue to @Ayush80555 @AkshitMital

**Comment by AkshitMital** [comment]
But I started working on this issue before it was assigned to @Ayush80555 and now I have fixed it too.

**Comment by Akshatchaube01** [comment]
Next time, make sure you get the issue assigned first and then start working on it. 
I 'll check the PR in the morning @AkshitMital

**Comment by AkshitMital** [comment]
Thank you very much @Akshatchaube01 ! I will keep this in mind moving forward. I apologize for the inconvenience.

**Comment by AkshitMital** [comment]
Hey @Akshatchaube01, Did you check my pull request?

**Comment by AkshitMital** [comment]
@Akshatchaube01, Can you please assign this issue to me?

**Comment by Akshatchaube01** [comment]
@AkshitMital it has already been assigned to ayush-pandey, ,you can create another issue and get it assigned to yourself

**Comment by AkshitMital** [comment]
@Akshatchaube01 But I had solved this issue before it was assigned @ayush-pandey1. Do you want me to create this same issue and then get it assigned to myself?
