### ISSUE TITLE
Implement tilt js library on the image

### ISSUE THREAD

**Issue by karthiknadar1204** [AlgoManiacZ/AlgoManiacZ_Revamped#40]
<img width="692" alt="Screenshot 2023-10-15 at 7 28 50 PM" src="https://github.com/AlgoManiacZ/AlgoManiacZ_Revamped/assets/95973644/c0c84cb1-f9eb-4b71-b789-ee33b8ef2d39">

Refer the tilt js documentation , if need any help, feel free to reach out

**Comment by ayush-pandey1** [comment]
Hey Akshat,

I would love to contribute to this issue, i've added tilt js.

kindly assign this issue.

**Comment by Akshatchaube01** [comment]
@Ayush80555 sure go ahead

**Comment by ayush-pandey1** [comment]
https://github.com/AlgoManiacZ/AlgoManiacZ_Revamped/assets/116146717/2164f876-6f3b-4b90-8ab9-2ea532443677

@Akshatchaube01  Is this okay or should i  make any changes?

**Comment by Akshatchaube01** [comment]
@Ayush80555 Looks good

**Comment by ayush-pandey1** [comment]
![image](https://github.com/AlgoManiacZ/AlgoManiacZ_Revamped/assets/116146717/76ff2ff9-338c-4f21-94e7-06d3a99c6c23)

Hey @Akshatchaube01 

I'm facing this error, can you assist me on this

**Comment by Ayush80555** [comment]
I made a pull request kindly review it and let me know if that's correct.

**Comment by ayush-pandey1** [comment]
Hey, @Akshatchaube01 can you please review my PR and merge it.
thanks
