### ISSUE TITLE
Hero Section

### ISSUE THREAD

**Issue by durgaprasad118** [AlgoManiacZ/AlgoManiacZ_Revamped#5]
I'd like to create a responsive  Hero Section

**Comment by Akshatchaube01** [comment]
Sure, You can work on this issue.

**Comment by durgaprasad118** [comment]
Assets are not there. Can I use similar ones

**Comment by Akshatchaube01** [comment]
yeah sure

**Comment by Akshatchaube01** [comment]
The assets are here : https://github.com/AlgoManiacZ/AlgoManiacZ_Revamped/tree/main/algoManiacZ/src/assets
If you feel some assets are missing, then you can use similar assets from your end

**Comment by durgaprasad118** [comment]
Yep, few are missing I've added them. Thankyou
