### ISSUE TITLE
Create a contribution.md file 

### ISSUE THREAD

**Issue by Akshatchaube01** [AlgoManiacZ/AlgoManiacZ_Revamped#53]
Add the following details in the contribution.md file :
1) First get the issue assigned and then submit a PR 
2) Share the preview of the changes when you submit a PR , it can be in the form of screenshots or videos
3) Also, refer the instructions in the readme.md to make the PR

**Comment by moulik10sharma** [comment]
Can you assign this issue to me? I would like to work on it if possible @Akshatchaube01
