### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by govardhan-26** [AlgoManiacZ/AlgoManiacZ_Revamped#6]
I would like to create the Home Page

**Comment by Akshatchaube01** [comment]
Sure, You can work on this

**Comment by tejanamala15** [comment]
Hey! Are you creating just the 'Home page' or are you working on the 'About us' page too?

**Comment by durgaprasad118** [comment]
@tejanamala15 About us page is done  just the home page which has (Name and discord link in the center).

**Comment by tejanamala15** [comment]
Okay, so can I work on the Home page is About page is done?

**Comment by durgaprasad118** [comment]
@govardhan-26  is assigned for it right?

**Comment by govardhan-26** [comment]
@tejanamala15 I am working on the Home page !

**Comment by govardhan-26** [comment]
@Akshatchaube01 Can we close this issue ?

**Comment by Akshatchaube01** [comment]
Yes
