### ISSUE TITLE
Blob like appearance 

### ISSUE THREAD

**Issue by Akshatchaube01** [AlgoManiacZ/AlgoManiacZ_Revamped#61]
Give a blob like appearance to the blocks on both ends, should look something like this:
![Blob](https://github.com/AlgoManiacZ/AlgoManiacZ_Revamped/assets/92796050/af78fcac-76da-4c07-a2e2-940abcdc7250)

**Comment by Hardik2972** [comment]
I want to fix this can you assign it to me

**Comment by Akshatchaube01** [comment]
Sure ! go ahead
