### ISSUE TITLE
Speaker Card Enhancement

### ISSUE THREAD

**Issue by Akshatchaube01** [AlgoManiacZ/AlgoManiacZ_Revamped#62]
The speaker Card should look something like this : 
![speaker-card](https://github.com/AlgoManiacZ/AlgoManiacZ_Revamped/assets/92796050/453d1651-bbda-4cef-b338-39ff71053240)

**Comment by shoaib-31** [comment]
@Akshatchaube01 I want to work on this issue, Please assign it to me.

**Comment by Akshatchaube01** [comment]
Sure ! Go ahead

**Comment by shoaib-31** [comment]
@Akshatchaube01 You only want this view in desktop view, right? And the current view on phone and tablet. Please clarify.

**Comment by Akshatchaube01** [comment]
We want it to be responsive :) @shoaib-31

**Comment by shoaib-31** [comment]
So like, same card will be in phone view? I am asking because in phones we can't hover over it ;)

**Comment by Akshatchaube01** [comment]
Ohh right, then don't change it for phone/tablet view @shoaib-31

**Comment by shoaib-31** [comment]
@Akshatchaube01 Are you sure, you don't want linkedIn and Github icon on newer cards?
It looks like this:
[Screencast from 21-10-23 07:17:15 PM IST.webm](https://github.com/AlgoManiacZ/AlgoManiacZ_Revamped/assets/103197883/a4f81604-870f-4eda-b943-7d7fbe027529)

**Comment by Akshatchaube01** [comment]
Looks great ! No need to add the icons, we can add them in other issues later on @shoaib-31

**Comment by shoaib-31** [comment]
@Akshatchaube01 I've linked a PR. Take a look :smile:
