### ISSUE TITLE
Scrollbar enhancement

### ISSUE THREAD

**Issue by Akshatchaube01** [AlgoManiacZ/AlgoManiacZ_Revamped#65]
The enhanced scrollbar should look something like this :
![scrollbar](https://github.com/AlgoManiacZ/AlgoManiacZ_Revamped/assets/92796050/2672e3b0-5370-467e-9bbb-a854721fe31b)

**Comment by Arceen** [comment]
Hey! I can do this. Can you assign this to me?

**Comment by Akshatchaube01** [comment]
Sure !

**Comment by Arceen** [comment]
Hey @Akshatchaube01 ! I've made a PR. Please check to see if its good. Thanks!
